import Head from 'next/head'
import classnames from 'classnames/bind'

import styles from './style.module.scss'

// Variables
const cx = classnames.bind(styles)

export default function Home() {
  return (
    <div className={cx('home')}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>hello world!</div>
    </div>
  )
}
